src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_post = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Sujet $sujet = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $user = null;

    ///////////////////// construct /////////////////////
    public function __construct()
    {
        $this->date_post = new \DateTime();
    }
    /////////////////////////////////////////////////////

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): static
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDatePost(): ?\DateTimeInterface
    {
        return $this->date_post;
    }

    public function setDatePost(\DateTimeInterface $date_post): static
    {
        $this->date_post = $date_post;

        return $this;
    }

    public function getSujet(): ?Sujet
    {
        return $this->sujet;
    }

    public function setSujet(?Sujet $sujet): static
    {
        $this->sujet = $sujet;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Sujet.php
<?php

namespace App\Entity;

use App\Repository\SujetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SujetRepository::class)]
class Sujet
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_création = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_update = null;

    #[ORM\Column(length: 255)]
    private ?string $intro = null;

    #[ORM\ManyToOne(inversedBy: 'sujets')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $user = null;

    /**
     * @var Collection<int, Post>
     */
    #[ORM\OneToMany(targetEntity: Post::class, mappedBy: 'sujet', orphanRemoval: true)]
    private Collection $posts;

    ///////////////////// construct /////////////////////
    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->date_création = new \DateTime();
        $this->date_update = new \DateTime();
    }
    /////////////////////////////////////////////////////


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateCréation(): ?\DateTimeInterface
    {
        return $this->date_création;
    }

    public function setDateCréation(\DateTimeInterface $date_création): static
    {
        $this->date_création = $date_création;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(\DateTimeInterface $date_update): static
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(string $intro): static
    {
        $this->intro = $intro;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setSujet($this);
        }

        return $this;
    }

    public function removePost(Post $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getSujet() === $this) {
                $post->setSujet(null);
            }
        }

        return $this;
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\Sujet;
use App\Form\NewPostType;
use App\Form\NewSujetType;
use App\Repository\PostRepository;
use App\Repository\SujetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ForumController extends AbstractController
{
  #[Route('/forum', name: 'app_forum')]
  public function index(SujetRepository $sujetRepository): Response
  {
    $sujets = $sujetRepository->findBy([], ["date_update" => "DESC"]);

    return $this->render('forum/index.html.twig', [
      "page_title" => "Bienvenue sur le forum",
      "sujets" => $sujets,
    ]);
  }

  #[Route('/forum/{titre}', name: 'sujet')]
  public function sujetContent(Request $request, PostRepository $postRepository, EntityManagerInterface $entityManager, SujetRepository $sujetRepository, Sujet $sujet): Response
  {
    $posts = $postRepository->findBy(["sujet" => $sujet]);

    // formulaire de nouveau post
    $post = new Post;

    $formNewPost = $this->createForm(NewPostType::class, $post);
    $formNewPost->handleRequest($request);

    if ($formNewPost->isSubmitted() && $formNewPost->isValid()) {

      // vérifie que l'utilisateur remplit bien le formulaire depuis le site. 
      if (isset($_SERVER["HTTP_REFERER"]) && strpos($_SERVER["HTTP_REFERER"], '127.0.0.1:8000')) {
        // vérification honey pot
        if (isset($_POST["email"]) && empty($_POST["email"])) {

          $post->setUser($this->getUser());
          $post->setSujet($sujet);

          $entityManager->persist($post);
          $entityManager->flush();
          return $this->redirectToRoute('sujet', ['titre' => $sujet->getTitre()]);
        } else {
          return $this->redirectToRoute('bot_detected');
        }
      } else {
        return $this->redirectToRoute('bot_detected');
      }
    }

    return $this->render('forum/sujet.html.twig', [
      "page_title" => $sujet->getTitre(),
      "sujet" => $sujet,
      "posts" => $posts,
      "form" => $formNewPost,
    ]);
  }

  #[Route('/sujet/new', name: 'new_sujet')]
  public function new_sujet(Request $request, EntityManagerInterface $entityManager): Response
  {
    // formulaire de nouveau sujet
    $sujet = new Sujet;

    $formNewSujet = $this->createForm(NewSujetType::class, $sujet);
    $formNewSujet->handleRequest($request);

    if ($formNewSujet->isSubmitted() && $formNewSujet->isValid()) {

      // vérifie que l'utilisateur remplit bien le formulaire depuis le site. 
      if (isset($_SERVER["HTTP_REFERER"]) && strpos($_SERVER["HTTP_REFERER"], '127.0.0.1:8000')) {
        // vérification honey pot
        if (isset($_POST["email"]) && empty($_POST["email"])) {

          $sujet->setUser($this->getUser());

          $entityManager->persist($sujet);
          $entityManager->flush();
          return $this->redirectToRoute('sujet', ['titre' => $sujet->getTitre()]);
        } else {
          return $this->redirectToRoute('bot_detected');
        }
      } else {
        return $this->redirectToRoute('bot_detected');
      }
    }

    return $this->render('forum/newSujet.html.twig', [
      "page_title" => "Nouveau topic",
      "form" => $formNewSujet,
    ]);
  }
}

templates/forum/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Forum
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/forum.css') }}" />
{% endblock %}

{% block body %}
{% if app.user %}
<a id="new_sujet" href="{{ path('new_sujet') }}"><i class="fa-solid fa-circle-plus"></i> &nbsp; créer un nouveau
  topic</a>
{% endif %}

<section id="forumContent">
  {% for sujet in sujets %}
  <div class="sujet-link">
    <a href="{{ path('sujet', { titre: sujet.titre }) }}">
      <strong>{{ sujet.titre }}</strong>
      <p>{{ sujet.intro }}</p>
    </a>
    <div class="sujet-details">
      <p>créé le {{ sujet.dateCréation|date('d/m/y') }}</p>
      <p>
        par 
        {% if sujet.user is defined and sujet.user is not empty %}
        <a class="pseudo" href="{{ path('profile_user', { pseudo: sujet.user }) }}">{{ sujet.user }}</a>
        {% else %}
        anonyme
        {% endif %}
          
      </p>
      <p>{{ sujet.posts|length }} posts</p>
    </div>
  </div>
  {% endfor %}
</section>
{% endblock %}

templates/forum/newSujet.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ page_title }}
{% endblock %}

{% block stylesheets %}
  <link rel="stylesheet" href="{{ asset('css/forum.css') }}" />
{% endblock %}

{% block body %}
  {{ form_start(form) }}
  {{ form_row(form.titre) }}
  {{ form_row(form.intro) }}

    <input type="hidden" name="email"/>

  <button type="submit">Créer le topic</button>

  {{ form_end(form) }}
{% endblock %}

templates/forum/sujet.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ sujet.titre }}
{% endblock %}

{% block stylesheets %}
  <link rel="stylesheet" href="{{ asset('css/forum.css') }}" />
{% endblock %}

{% block body %}
  <p class="intro">{{ sujet.intro }}</p>

  <section id="sujetContent">
    {% for post in posts %}
      {% if post.user == app.user %}
      <div class="post my_post">
      {% else %}
      <div class="post">
      {% endif %}

        <div class="post-infos">
          {% if post.user is defined and post.user is not empty %}
          <a class="pseudo" href="{{ path('profile_user', { pseudo: post.user }) }}">{{ post.user }}</a>
          {% else %}
          anonyme
          {% endif %}
          <p class="date">
, 
{% set dateActuelle = "now" | date('m/d/y') %}
{% set dateMessage = post.datePost | date('m/d/y') %}
{% set diff = date("now").diff(post.datePost) %}
{% set daysdiff = diff.days %}

{% if daysdiff == 0 %}
aujourd'hui

{% elseif daysdiff == 1 %}
hier

{% else %}
il y a {{daysdiff}} jours
{% endif %}
          </p>
        </div>
        <p class="contenu">{{ post.contenu }}</p>
      </div>
    {% endfor %}
  </section>

{% if app.user is defined and app.user is not empty %}
  
  {{ form_start(form) }}
    <p>envoyer un commentaire</p>
  {{ form_row(form.contenu) }}

    <input type="hidden" name="email"/>

  <button type="submit">Envoyer</button>

  {{ form_end(form) }}
{% endif %}

{% endblock %}